// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZTg1paxoPM6TXxb1sYCinhXdJuZ5SkU',
    appId: '1:505185790243:android:2d10ef16906faf79214496',
    messagingSenderId: '505185790243',
    projectId: 'mynotes-flutter-leo',
    storageBucket: 'mynotes-flutter-leo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtIr4PaMxLXpzh4olltizFjFb_RstgbkQ',
    appId: '1:505185790243:ios:c8a759dcf488e240214496',
    messagingSenderId: '505185790243',
    projectId: 'mynotes-flutter-leo',
    storageBucket: 'mynotes-flutter-leo.appspot.com',
    iosClientId: '505185790243-2tgdea88igtvpvk203mcn5kl1li4kcaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
